vim9script
nnoremap <buffer> <Space>;r <ScriptCmd>RefreshContents()<CR>


def RefreshContents()
    var result: dict<list<dict<string>>>
    for file in system("git ls-files '*.md'")->split("\n")
        if file == 'README.md'
            continue
        endif
        const metadata: dict<string> = HandleMetadata(file, readfile(file, '', 3))
        if !result->has_key(metadata.category)
            result[metadata.category] = []
        endif
        result[metadata.category]->add(metadata)
    endfor
    result->values()->sort((a, b) => a[0].title > b[0].title ? 1 : -1)

    var lines_to_write: list<string> =<< trim END
    % TILs (today I learned)

    <!--
    generated by vimrc. DO NOT EDIT.

    " usage:
    " cd dir of this file,
    :source ./vimrc
    " then pressing <Leader>;r to refresh content.
    -->

    Idea comes from <https://til.simonwillison.net/> (which comes from others...)

    ---

    END
    for item in result->keys()->sort((a, b) => a > b ? 1 : -1)
        lines_to_write->add(printf('- %s', item))
        for article in result[item]
            const suffix = article.date->empty() ? '' : printf(' %s', article.date)
            lines_to_write->add(printf('  - [%s](%s)%s', article.title, article.filename, suffix))
        endfor
    endfor
    writefile(lines_to_write, 'README.md')
    if bufname() == 'README.md'
        # reload
        e
    else
        if &modified
            sp
        endif
        e README.md
    endif
enddef


def HandleMetadata(filename: string, args: list<string>): dict<string>
    var useful_args: list<string>
    for arg in args
        # https://pandoc.org/MANUAL.html#metadata-blocks
        # NOTE we do not handle multiple-lines.
        if arg->match('\v^\%($| )') < 0
            break
        endif
        # skip leading "% "
        useful_args->add(arg[2 : ])
    endfor
    var title = useful_args->get(0, '')
    # the second line is author: we don't use it...
    const date = useful_args->get(2, '')
    if title->empty()
        title = filename->substitute('\v^.*/', '', '')
    endif
    return {
        title: title,
        date: date,
        category: filename->substitute('\v/[^/].*$', '', ''),
        filename: filename,
        }
enddef
