name: gh-pages

on:
  push:
    branches:
      - 'main'

jobs:
  build-site:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
    - name: Check out repo's default branch
      uses: actions/checkout@v3
    - name: Build site
      run: |-
        set -e
        git branch -D pages || true
        git checkout -b pages

        podman run --name pandoc --init --rm -dt --entrypoint= docker.io/pandoc/core tail -f
        (cd blog && ./build.sh;)
        podman stop pandoc

        git add -f 'blog/*.html'
        git config user.name 'github actions'
        git config user.email ''
        git commit -m 'auto-build'

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_branch: pages
